### ISSUE TITLE
Criar versão 'kids' acessível como atividade pedagógica

### ISSUE THREAD

**Issue by luiguild** [raphamorim/origamijs#2]
Poderíamos criar uma versão infantil para ser utilizada no aprendizado da ferramenta.

Sugiro a análise do Thimble[1](da Mozilla) como plataforma educacional

1 - http://thimble.mozilla.org/

**Comment by raphamorim** [comment]
Concordo, seria criar uma atividade onde usa o origamijs como arquivo né?
Talvez seria interessante fazer um wrapper para os métodos do origami.js ficarem em portugues também.

Ex:

``` js
origami('#id-elemento')
   .quadrado(10, 30, 40, {
       bordaCor: "azul", 
       bordaTamanho: "1px", 
       fundoCor: "vermelho"
   })
   .desenhar();
```

**Comment by luiguild** [comment]
Acho que a localização/tradução é o primeiro passo. A utilização da ferramenta como arquivo dentro do Thimble é a melhor (e mais prática) maneira que eu consigo pensar agora...

**Comment by raphamorim** [comment]
Colocarei como feature para segunda release.
