### ISSUE TITLE
Adjusments Layout Home

### ISSUE THREAD

**Issue by raphamorim** [raphamorim/origamijs#4]
Layout by @ntmedina

Need some adjusts in home page.
- Resposible
- Missing Right Fonts
- Missing Features blocks
### Desktop Version

![img_2016-03-18 12 56 33](https://cloud.githubusercontent.com/assets/3630346/14581932/a0cfeac0-03d0-11e6-929e-f8caad3daea8.jpg)
### Mobile Version

![website-mobile](https://cloud.githubusercontent.com/assets/3630346/14581947/fe902ac6-03d0-11e6-9ed5-88733eff5cbf.png)

**Comment by raphamorim** [comment]
cc// @jjaderg @afonsopacifer

**Comment by raphamorim** [comment]
@afonsopacifer, you know something which @mvfsilva can help you?

**Comment by afonsopacifer** [comment]
@raphamorim, @mvfsilva Yes! 
Let me finish my first Pull Request..

If they want to follow , I am working in the "structure-refactor" branch :)

**Comment by afonsopacifer** [comment]
[Nav component refactored](https://github.com/raphamorim/origamijs.com/commit/2e0636cdfa34d5d4c2c8d3d7e0c607c19f9df41a)

Preview:

![screen shot 2016-04-16 at 11 45 54 pm](https://cloud.githubusercontent.com/assets/6748866/14584769/784adee0-042d-11e6-9aff-d812e910081f.png)

**Comment by mvfsillva** [comment]
nice @afonsopacifer!

**Comment by afonsopacifer** [comment]
Thank's @mvfsilva <3

Gradually this evolving : )

![screen shot 2016-04-17 at 2 27 24 am](https://cloud.githubusercontent.com/assets/6748866/14585279/1896236c-0444-11e6-97e0-f954f3c6dc69.png)

**Comment by jdrgoms** [comment]
I'm proud of you my friend @afonsopacifer

**Comment by raphamorim** [comment]
Any news @afonsopacifer ?

**Comment by mvfsillva** [comment]
Amazing analysis of metrics! congratulations @afonsopacifer;
