### ISSUE TITLE
Page: Home

### ISSUE THREAD

**Issue by raphamorim** [raphamorim/origamijs#9]
Finish this page
### Desktop Version

![img_2016-03-18 12 56 33](https://cloud.githubusercontent.com/assets/3630346/14581932/a0cfeac0-03d0-11e6-929e-f8caad3daea8.jpg)
### Mobile Version

![website-mobile](https://cloud.githubusercontent.com/assets/3630346/14581947/fe902ac6-03d0-11e6-9ed5-88733eff5cbf.png)

**Comment by jdrgoms** [comment]
I'm in this battle :hand:

**Comment by raphamorim** [comment]
Ref: #12

**Comment by raphamorim** [comment]
After 5efa9fc commit adjustmens, I think desktop has a stable version, missing some layouts adjuments. However we can proced to mobile version && desktop adjusments
